/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux recas-uniba-hpc-05.ba.infn.it 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 10:35:19 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define CXX "g++"
#define COMPILER "/usr/bin/g++"
#define COMPILERVERS "gcc447"
#define MAKESHAREDLIB  "cd $BuildDir ; g++ -c $Opt -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles ; g++ $ObjectFiles -shared -Wl,-soname,$LibName.so -m64 -O2  -Wl,--no-undefined -Wl,--as-needed $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++ -c  -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles; g++ $ObjectFiles -m64 -O2  -Wl,--no-undefined -Wl,--as-needed -o $ExeName $LinkedLibs -lm -ldl  -pthread   -rdynamic"
#define CXXOPT "-O2"
#define CXXDEBUG "-g"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lCint -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o"
#define SOEXT "so"
